apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.8.89
    helm:
      values: |
        controller:
          serviceType: ClusterIP
          admin:
            password: "admin123"
          ingress:
            enabled: false
          extraPorts:
            - name: https
              port: 8443
              targetPort: 8080  # Route external 8443 to Jenkins on 8080

        persistence:
          enabled: true
          size: 20Gi

        serviceAccount:
          create: true

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
