apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-custom
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/KoalbyMQP/infrastructure
    targetRevision: HEAD
    path: applications/manifests/vaultwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
  - CreateNamespace=true
